
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
target 'CWWebViewControllerLib_Example' do
  pod 'CWWebViewControllerLib', :path => '../'

  target 'CWWebViewControllerLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
